import { BrainCircuit, ShieldCheck, TriangleAlert, Users } from 'lucide-react';
import AlertList from './AlertList';
import TrendChart from './TrendChart';
import { alerts } from './data';
import { Card, SectionTitle } from './ui';

const metrics = [['Total Personnel','2,450','+ 38 this month',<Users/>,'blue'],['Needs Attention','18','+ 5 this week','🏆','amber'],['Overall Wellness','87%','● Good',<ShieldCheck/>,'green'],['Active Alerts','7','View all alerts',<TriangleAlert/>,'purple']];
const tones = { blue:'bg-blue-50 text-blue-700', amber:'bg-amber-50 text-amber-700', green:'bg-emerald-50 text-emerald-700', purple:'bg-purple-50 text-purple-700' };

export default function Dashboard({ navigate }) { return <><div className="mb-7 flex justify-between"><div><h1 className="font-display text-2xl font-extrabold">Welcome, Officer 👋</h1><p className="m-0 text-sm text-slate-500">Here’s the overall welfare overview</p></div><select className="rounded-lg border border-slate-200 bg-white px-3 text-sm"><option>September 2026</option><option>August 2026</option></select></div><section className="mb-4 grid grid-cols-2 gap-3 md:grid-cols-4">{metrics.map(([title,value,note,icon,tone]) => <Card key={title}><div className={`grid h-8 w-8 place-items-center rounded-lg ${tones[tone]}`}>{icon}</div><p className="mb-1 mt-2 text-xs">{title}</p><b className="font-display text-2xl">{value}</b><small className="mt-2 block text-[11px] text-emerald-700">{note}</small></Card>)}</section><section className="mb-4 grid gap-4 lg:grid-cols-[1.6fr_.9fr]"><Card><SectionTitle action={<select className="border p-1 text-xs"><option>Overall trend</option></select>}>Wellness Trend</SectionTitle><TrendChart/></Card><Card><SectionTitle>Personnel Status</SectionTitle><div className="flex items-center justify-center gap-5 pt-5"><div className="grid h-22 w-22 place-items-center rounded-full bg-[conic-gradient(#57b346_0_77%,#f7c52a_77%_93%,#ff8b12_93%_98%,#f03c2b_98%)]"><i className="h-14 w-14 rounded-full bg-white"/></div><div className="text-xs leading-7">🟢 <b>Stable</b><br/>🟡 Needs attention<br/>🟠 Elevated concern<br/>🔴 Immediate support</div></div></Card></section><section className="grid gap-4 lg:grid-cols-[1.6fr_.9fr]"><Card><SectionTitle action={<button onClick={() => navigate('AI Insights')} className="text-xs text-blue-700">View Details</button>}>AI Insights</SectionTitle><div className="flex gap-3 rounded-lg bg-blue-50 p-3 text-xs leading-6"><BrainCircuit className="shrink-0 text-blue-700"/><div>AI analysis indicates increased workload in Unit Bravo and reduced leave utilization in 3 units.<b className="mt-2 block">Top recommendations</b>✓ Review workload distribution<br/>✓ Encourage leave utilization<br/>✓ Schedule welfare check-ins</div></div></Card><Card><SectionTitle action={<button onClick={() => navigate('Alerts')} className="text-xs text-blue-700">View All</button>}>Recent Alerts</SectionTitle><AlertList data={alerts}/></Card></section></>; }
